name:                forsyde-deep-examples
version:             0.1.0.0
github:              "githubuser/forsyde-deep-examples"
license:             BSD3
author:              "Ingo Sander"
maintainer:          "ingo@kth.se"
copyright:           "2019 Ingo Sander"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/forsyde-deep-examples#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - forsyde-deep
  
executables:
  forsyde-deep-examples-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-deep-examples

tests:
  forsyde-deep-examples-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - forsyde-deep-examples
